### ISSUE TITLE
在k8s上部署基本问题

### ISSUE THREAD

**Issue by yjustdo** [pnboot/gzzd#5]
在k8s上部署，主要是参考作者的两个yaml文件[](https://github.com/pnboot/gzzd/tree/main/doc/k8s/yaml)。对于其中一些参数配置我结合自己的经历做一些说明。在deploy.yaml中
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: serverside-ui
  name: serverside-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serverside-ui
  template:
    metadata:
      labels:
        app: serverside-ui
    spec:
      containers:
        - env:
            - name: masterUrl
              value: "https://masterIP:6443" #这里要填写你自己的k8s集群的master节点的ip
            - name: token
              value: "" #要注意24小时可能失效，可能需要重新生成新的，重新配置
            - name: spring.profiles.active
              value: test
            - name: namespace
              value: test
            - name: proxy.server.uiIp
              value: ""#这里也填master节点的ip，一定要能从外部访问
            - name: proxy.server.nodePort
              value: "31113"
            - name: proxy.server.proxyIp
              value: "serverside-ui"
          image: registry.cn-hangzhou.aliyuncs.com/19/serverside-ui:0.0.1
          imagePullPolicy: Always
          name: serverside-ui
```
按上面配置，工具这边就没什么问题了。下面结合自己的经历谈一下。
首先，要想让工具能看到你的应用，**必须通过deployment部署，直接部署一个pod是不行的**，网页上是看不到应用的
第二，**应用运行的pod必须要能wget**，因为启动脚本里面有命令通过wget下载东西
第三，运行不正常的话看日志有两个，`kubectl describe pod pod的名字`可以看agent有没有connected。另外就是exec到你的应用pod，去//kfz/gzzd/agent-bin/logs下看bistoury-agent.out

都顺利的话，就可以访问http://masterIP:31191进入页面了
[](https://imgtu.com/i/hS2ztK)
感谢作者大佬的开源！
